language: java

jdk:
    - oraclejdk8

env:
    - TERM=dumb

before_install:
    - ./install_flatbuffers.sh

after_success:
    - ./gradlew jacocoTestReport coveralls

notifications:
    email:
        on_success: always
        on_failure: always
